
const PopPostData = [
    {
        id:1,
        img:'images/food1.jpg',
        category:'Carpainter',
        date:'Dec 07 2022',
        heading:'Your most unhappy customers are your greatest source of learning.',
        desc:'Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.',
        userProfile:'images/pro1.png',
        userName:'Mohammad Waris',
        userPosition:'Author/Writer',
    },
    {
        id:2,
        img:'images/food2.jpg',
        category:'Plant',
        date:'Dec 07 2022',
        heading:'Your most unhappy customers are your greatest source of learning.',
        desc:'Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.',
        userProfile:'images/pro1.png',
        userName:'Mohammad Waris',
        userPosition:'Author/Writer',
    },
    {
        id:3,
        img:'images/food3.jpg',
        category:'Food',
        date:'Dec 07 2022',
        heading:'Your most unhappy customers are your greatest source of learning.',
        desc:'Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.',
        userProfile:'images/pro1.png',
        userName:'Mohammad Waris',
        userPosition:'Author/Writer',
    },
    {
        id:4,
        img:'images/food4.jpg',
        category:'Architec',
        date:'Dec 07 2022',
        heading:'Your most unhappy customers are your greatest source of learning.',
        desc:'Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.',
        userProfile:'images/pro1.png',
        userName:'Mohammad Waris',
        userPosition:'Author/Writer',
    },
    {
        id:5,
        img:'images/img4.webp',
        category:'Architec',
        date:'Dec 07 2022',
        heading:'Your most unhappy customers are your greatest source of learning.',
        desc:'Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.',
        userProfile:'images/pro1.png',
        userName:'Mohammad Waris',
        userPosition:'Author/Writer',
    },
    {
        id:6,
        img:'images/img5.webp',
        category:'Architec',
        date:'Dec 07 2022',
        heading:'Your most unhappy customers are your greatest source of learning.',
        desc:'Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.',
        userProfile:'images/pro1.png',
        userName:'Mohammad Waris',
        userPosition:'Author/Writer',
    },
    // {
    //     id:7,
    //     img:'images/food1.jpg',
    //     category:'Food',
    //     date:'Dec 07 2022',
    //     heading:'Your most unhappy customers are your greatest source of learning.',
    //     desc:'Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.',
    //     userProfile:'images/pro1.png',
    //     userName:'Mohammad Waris',
    //     userPosition:'Auther/Writer',
    // },
]

export default PopPostData
